
method: grid

metric:
    name: loss
    goal: minimize

parameters:
    lr:
        values:
            - 0.001
            - 0.0001
    patience:
        values:
            - 2
            - 5
            - 10
    order_mag_reduce:
        values:
            - 10
            - 100
    nb_layers:
        values:
            - 2
            - 4
    num_heads:
        values:
            - 2
            - 4
            - 8
    hidden_channels:
        values:
            - 128
            - 256


